export const usersAlpha = [
  { name: "Matan Elimelech", team: "Echo"},
  { name: "Kenneth Dan Weinberg Waks", team: "Charlie"},
  { name: "Liat Agam", team: "Charlie"},
  { name: "Ben Cohen", team: "Charlie"},
  { name: "Nadav Zvaig", team: "Hotel"},
  { name: "Adi Levin", team: "Charlie"},
  { name: "Yonatan Kra", team: "Charlie"},
  { name: "Safi Noah", team: "Hotel"},
  { name: "Priel Kasookar", team: "Charlie"},
  { name: "Tomer Messer", team: "Charlie"},
  { name: "Dan Beladev", team: "Charlie"},
  { name: "Moshe Piamenta", team: "Charlie"},
  { name: "Ron Gabbay", team: "Charlie"},
  { name: "Yaniv Shimoni", team: "Alpha"},
  { name: "Shani Goladman", team: "Echo"},
  { name: "Assaf Biran", team: "Charlie"},
  { name: "Yael Zlotnik", team: "Echo"},
  { name: "Yinon Reiss", team: "Hotel"},
  { name: "Dave Bitton", team: "Echo"},
  { name: "Matan Zari", team: "Echo"},
  { name: "Carmel Cappon", team: "Alpha"},
  { name: "Daniel Kissos", team: "Echo"},
  { name: "Oran Rozenbaum", team: "Hotel"},
  { name: "Omri Ovadia", team: "Echo"},
  { name: "Shay Mohar", team: "Echo"},
  { name: "Eran Ezer", team: "Hotel"},
  { name: "David Vinter", team: "Hotel"},
  { name: "Daniel Yaakov", team: "Echo"},
  { name: "Tomer Picker", team: "Echo"},
];

export default usersAlpha;
