export const usersAlpha = [
    //   "Matan Elimelech",
      "Kenneth Dan Weinberg Waks",
      "Liat Agam",
      "Ben Cohen",
      "Nadav Zvaig",
      "Adi Levin",
      "Yonatan Kra",
      "Safi Noah",
      "Priel Kasookar",
      "Tomer Messer",
      "Dan Beladev",
      "Moshe Piamenta",
      "Ron Gabbay",
      "Yaniv Shimoni",
      "Shani Goladman",
      "Assaf Biran",
      "Yael Zlotnik",
      "Yinon Reiss",
      "Dave Bitton",
      "Matan Zari",
      "Carmel Cappon",
      "Daniel Kissos",
      "Oran Rozenbaum",
      "Omri Ovadia",
      "Shay Mohar",
      "Eran Ezer",
      "David Vinter",
      "Daniel Yaakov",
      "Tomer Picker",
    ];

    export default usersAlpha;
